<?php declare(strict_types=1);

namespace Karser\PayumSaferpay;

interface Constants
{
    const INTERFACE_PAYMENT_PAGE = 'PAYMENT_PAGE';
    const INTERFACE_TRANSACTION = 'TRANSACTION';

    const STATUS_PENDING = 'PENDING';
    const STATUS_AUTHORIZED = 'AUTHORIZED';
    const STATUS_CAPTURED = 'CAPTURED';
    const STATUS_CANCELED = 'CANCELED';
    const STATUS_ABORTED = 'ABORTED';
    const STATUS_FAILED = 'FAILED';

    const TYPE_PURCHASE = 'PURCHASE';
    const TYPE_PAYMENT = 'PAYMENT';
    const TYPE_REFUND = 'REFUND';

    const ALIAS_TYPE_CARD = 'CARD';
    const ALIAS_TYPE_BANK_ACCOUNT = 'BANK_ACCOUNT';
    const ALIAS_TYPE_POSTFINANCE = 'POSTFINANCE';
    const ALIAS_TYPE_TWINT = 'TWINT';

    const ALIAS_ID_GENERATOR_MANUAL = 'MANUAL';
    const ALIAS_ID_GENERATOR_RANDOM = 'RANDOM';
    const ALIAS_ID_GENERATOR_RANDOM_UNIQUE = 'RANDOM_UNIQUE';

    const LS_IF_ALLOWED_BY_SCHEME = 'IF_ALLOWED_BY_SCHEME';
    const LS_WITH_LIABILITY_SHIFT = 'WITH_LIABILITY_SHIFT';
}
